---
- name: add mongodb apt key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10

- name: add mongodb source
  apt_repository:
    repo: 'deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse'
    state: present

- name: install mongodb
  apt:
    name: mongodb-org
    state: present
    update_cache: true
    cache_valid_time: 3600
