#!/usr/bin/env python

import glob

origHostText = """127.0.0.1 localhost vb

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts


# Generated by:
# ansible/copy_inv_hosts_to_local.py

"""

def addHosts(origText):
    ipHostMap = {}
    allHostFiles = glob.glob("inventories/*/hosts")
    for hostFile in allHostFiles:
        lines = [line.rstrip('\n') for line in open(hostFile)]
        for line in lines:
            foundIp = None
            fragments = line.split()
            for fragment in fragments:
                if 'ansible_ssh_host' in fragment:
                    foundIp = fragment.split('ansible_ssh_host=')[1]
            if foundIp != None:
                if fragments[0][0] != '#':
                    ipHostMap[foundIp] = fragments[0]
    # found all hosts
    for ip, host in ipHostMap.iteritems():
        origText += "{} {}\n".format(ip, host)
    with open('/tmp/hosts', 'w') as f:
        f.write(origText)

if __name__ == '__main__':
    addHosts(origHostText)
    print 'Generated. Run:'
    print 'sudo cp /tmp/hosts /etc/hosts'
