---
# run as sudo
- hosts: web
  sudo: yes
  roles:
    - common
    - nodejs
    - { role: mysql, tags: [noncluster] }
    - { role: mongodb, tags: [noncluster] }
    - { role: memcached, tags: [noncluster] }
    - nfs_client

    # - { role: mysql, tags: [cluster] }
    # - { role: mongodb, tags: [cluster] }
    # - { role: memcached, tags: [cluster] }

# run as non-sudo
- hosts: web
  sudo: no
  roles:
    - rvm
