---
- name: shutdown rabbitmq to change cookie
  service:
    name: rabbitmq-server
    state: stopped

- name: ensure cookies are the same between all envs
  template:
    src: erlang.cookie.j2
    dest: /var/lib/rabbitmq/.erlang.cookie

- name: start rabbitmq-server
  service:
    name: rabbitmq-server
    state: started

- name: stop rabbitmq-server
  service:
    name: rabbitmq-server
    state: stopped

- name: create the ssl folder for rabbitmq
  file:
    path: /etc/rabbitmq/ssl/
    owner: rabbitmq
    group: rabbitmq
    mode: 0750
    state: directory

# - name: copy the ssl certificates
#   copy:
#     src: {{ item.src }}
#     dest: {{ item.dest }}
#     owner: rabbitmq
#     group: rabbitmq
#     mode: 0640
#     backup: yes
#   with_items:
#     - src: "{{ rabbitmq_cacert }}"
#       dest: "{{ rabbitmq_conf_ssl_options_cacertfile }}"
#     - src: "{{ rabbitmq_server_key }}"
#       dest: "{{ rabbitmq_conf_ssl_options_keyfile }}"
#     - src: "{{ rabbitmq_server_cert }}"
#       dest: "{{ rabbitmq_conf_ssl_options_certfile }}"

- name: generate the configuration of rabbitmq
  template:
    src: rabbitmq.config.j2
    dest: /etc/rabbitmq/rabbitmq.config
    owner: rabbitmq
    group: rabbitmq
    mode: 0644
    backup: yes

- name: start rabbitmq-server
  service:
    name: rabbitmq-server
    state: started
