---
- name: add rabbitmq apt key
  apt_key:
    url: https://www.rabbitmq.com/rabbitmq-signing-key-public.asc
    state: present

- name: add rabbitmq source
  apt_repository:
    repo: 'deb http://www.rabbitmq.com/debian/ testing main'
    state: present

- name: install rabbitmq
  apt:
    name: rabbitmq-server
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: enable rabbitmq management plugin
  rabbitmq_plugin: names=rabbitmq_management state=enabled

- name: add admin user to rabbitmq
  rabbitmq_user:
    user: admin
    password: admin
    tags: administrator
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
