---
- apt: update_cache=yes cache_valid_time=3600

- name: install mysql
  action: apt pkg={{ item }} state=present
  with_items:
    - mysql-server
    - mysql-client
    - libmysqlclient-dev
    - python-mysqldb

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
   - "{{ ansible_hostname }}"
   - 127.0.0.1
   - ::1
   - localhost
  when: ansible_hostname != 'localhost'

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
   - 127.0.0.1
   - ::1
   - localhost
  when: ansible_hostname == 'localhost'

- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
   - localhost
   - "{{ ansible_hostname }}"

- name: remove the MySQL test database
  mysql_db: db=test state=absent
  notify:
    - restart MySQL
