---
- stat: path={{google_apt_file}}
  register: google_apt_exists
  ignore_errors: True
  tags: ["packages","chrome"]

- name: Add Google Chrome key
  shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  when: google_apt_exists.stat.exists == False
  tags: ["packages","chrome"]

- name: Add Google Chrome repo
  copy: content="deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" dest={{google_apt_file}} owner=root group=root mode=644
  when: google_apt_exists.stat.exists == False
  tags: ["packages","chrome"]

- name: Update apt cache
  apt: update_cache=yes
  when: google_apt_exists.stat.exists == False
  tags: ["packages","chrome"]

- name: Install Google Chrome
  apt: pkg=google-chrome-stable state=installed
  tags: ["packages","chrome"]
