---
# common python modules
- name: install python dependencies
  action: apt pkg={{ item }} state=present
  with_items:
    - python-dev
    - python-pip
    - python-yaml

- name: install python modules
  pip: name={{ item }}
  with_items:
    - ipython
    - jupyter
    - youtube-dl
