---
# screen
- name: install screen
  apt:
    name: screen
    state: latest
    update_cache: true
    cache_valid_time: 3600

- name: configure screen
  copy:
    src: .screenrc
    dest: /home/ubuntu/.screenrc
    force: no
    owner: ubuntu
    group: ubuntu
