---
- apt: update_cache=yes cache_valid_time=3600

# common apt packages
- name: install apt packages without dependencies
  action: apt pkg={{ item }} state=present
  with_items:
    - git
    - gitk
    - htop
    - curl
    - openssh-server
    - imagemagick
