---
- name: install nfs client
  apt: pkg={{ item }} state=present
  with_items:
    - nfs-common

- name: create data folder
  file:
    path: /data
    state: directory

- name: create share folder
  file:
    path: /data/{{ item }}
    owner: ubuntu
    group: ubuntu
    state: directory
  with_items: groups['storage']

- name: mount server exported folder
  mount:
    name: /data/{{ item }}
    src: "{{ item }}:/data/{{ item }}"
    fstype: nfs
    opts: defaults
    state: mounted
  with_items: groups['storage']
