---
- name: build hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item]['ansible_ssh_host'] }} {{item}}"
    state: present
  when: hostvars[item]['ansible_ssh_host'] is defined
  with_items: groups['all']
