---
- name: make sure the known hosts file exists
  file:
    path: /home/ubuntu/.ssh/known_hosts
    state: touch

# hostvars[item]['ansible_ssh_host']
- name: scan known_hosts file
  shell: "ssh-keygen -f /home/ubuntu/.ssh/known_hosts -F {{ item }} | wc -l"
  with_items: groups['all']
  register: ssh_known_host_results
  when: inventory_hostname != "{{ item }}"
  ignore_errors: yes

- name: populate known_hosts file
  shell: "ssh-keyscan -t rsa {{ item.item }} 2>/dev/null >> /home/ubuntu/.ssh/known_hosts"
  with_items: ssh_known_host_results.results
  when: item.has_key('stdout') and item.stdout == "0"
